### PR TITLE
add config templating

### PR DESCRIPTION
**Pull request by saltydk**
Suggestion for resolving #109 whilst keeping IPv6 functionality.

### CODE REVIEW

**Comment by sammcj** [comment]
Any update on getting this merged @Tecnativa?

**Comment by pedrobaeza** [comment]
I don't get why you need all the `.template` stuff for the IPv6 thing.

**Comment by pedrobaeza** [comment]
Yeah, but for this I think there's no need of having 2 files. Just inject the environment variable on the file. Another think I don't like is the extra added package.

**Comment by saltydk** [comment]
As far as I know haproxy doesn't allow templating in bind, if that was what you were going for.

**Comment by pedrobaeza** [comment]
OK, what about the extra package?

**Comment by saltydk** [comment]
The alternative sed solution is posted in the issue but didn't get any feedback on which was preferred.

**Comment by pedrobaeza** [comment]
Then please proceed with one not adding more load to the container.

**Comment by saltydk** [comment]
Done.

**Comment by saltydk** [comment]
Removed the -f flag so it matches the current entrypoint logic https://github.com/docker-library/haproxy/blob/master/2.2/docker-entrypoint.sh

**Comment by pedrobaeza** [comment]
Is the CI fault related?

**Comment by saltydk** [comment]
It has error'ed for a while, don't think it is related to any of this PR.

**Comment by pedrobaeza** [comment]
@josep-tecnativa please check how to fix the CI in this project.

**Comment by saltydk** [comment]
Yeah, I can't find any faults. Should I change the default to be IPv6 enabled? Currently it fallbacks to IPv4 only.

**Comment by saltydk** [comment]
Given that the CI throws a IPv6 error:
>  Stderr:       | error during connect: Get "http://localhost:32768/v1.24/containers/ebcc16f045797cd6b7c937952c84bfbdfa9d034a206d0997162ceae82a75a0f6/json": read tcp [::1]:48582->[::1]:32768: read: connection reset by peer

**Comment by pedrobaeza** [comment]
Try to see. I think the IPv6 support was merged because a green CI.

**Comment by saltydk** [comment]
It is failing to install the test

> The current project could not be installed: No file/folder found for package docker-socket-proxy
   If you do not want to install the current project use --no-root

**Comment by saltydk** [comment]
I've inverted the setting but it didn't change anything. The PR that I made last time didn't fail as a PR but failed once merged so something must have happened in-between.

**Comment by saltydk** [comment]
Added back the -f flag since it doesn't work with the old entrypoint style.

**Comment by saltydk** [comment]
Made it a bit cleaner by replacing the built-in entrypoint. Still cannot fix the build-test.

**Comment by josep-tecnativa** [comment]
> Made it a bit cleaner by replacing the built-in entrypoint. Still cannot fix the build-test.

Why did you deleted the entrypoint in Dockerfile?

**Comment by saltydk** [comment]
I replaced the existing one since it was cleaner

**Comment by josep-tecnativa** [comment]
Check this out : https://github.com/Tecnativa/docker-socket-proxy/pull/116 . I think that by running `poetry update`, the error is fixed.

**Comment by saltydk** [comment]
Will do when I am back at the PC, thanks.

**Comment by pedrobaeza** [comment]
Well, now it's just rebase this branch over current master

**Comment by saltydk** [comment]
Done.

**Comment by saltydk** [comment]
No, it just replaces the script that was already present in the base image.

**Comment by josep-tecnativa** [comment]
> For reference: https://github.com/docker-library/haproxy/blob/2913aa63fe4594a441e41f13e2c820092064a032/2.2/alpine/Dockerfile#L100-L106

Understood, thank you for the clarification. From my side, it looks good, I'll merge it.

**Comment by jscheytt** [comment]
Thank you @saltydk @pedrobaeza @josep-tecnativa for getting this merged! The problem I was encountering in https://github.com/Tecnativa/docker-socket-proxy/issues/109 is solved by this if I set the env var `DISABLE_IPV6: "1"`.

Maybe we could add some info about this to the README?

**Comment by pedrobaeza** [comment]
Yes, can you please make a PR adding such information?

**Comment by jscheytt** [comment]
Sure: https://github.com/Tecnativa/docker-socket-proxy/pull/119

**Pull request merged**
