### PR TITLE
[ADD] 'no strict-limits' option in haproxy.cfg

### PR DESCRIPTION
**Pull request by josep-tecnativa**
This is to prevent FD limit errors during startup.
This PR fix https://github.com/Tecnativa/docker-socket-proxy/issues/134

### CODE REVIEW

**Comment by pedrobaeza** [comment]
CI is red

**Comment by powerman** [comment]
LGTM

**Comment by josep-tecnativa** [comment]
> LGTM

I'm trying to fix CI before merge

**Comment by josep-tecnativa** [comment]
Just for the record, the CI problems seems to be related [this issue] (https://github.com/haproxy/haproxy/issues/2684) posted by @proudier

**Comment by josep-tecnativa** [comment]
We should consider downgrading until the issue is fixed.

**Comment by josep-tecnativa** [comment]
ping @pedrobaeza this is ready to merge now

**Comment by pedrobaeza** [comment]
But this is undoing partially #130, but not removing root access. Is that "upgrade to TCP" totally needed for the general purpose? Anyway, everything (the upgrade to 3.0 and the HAProxy issue) seems to come from the same person, @proudier, so he can say if it's OK for him.

**Comment by proudier** [comment]
Given the lack of activity on the [HAproxy issue](https://github.com/haproxy/haproxy/issues/2684) and the obvious need to fix the main branch, I have no problem with the changes of #130 being reverted.

For a clearer GIT history, I think the whole PR should be [reverted](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request) instead of reverting the changes manually in different PR. If you're OK with this approach, I can create a "revert PR".

Upstream HAproxy images for version 2.2 and 2.3 already runs as root, so that part of the original PR isnt required anymore.

**Comment by pedrobaeza** [comment]
OK, let's revert it.

**Review by Mayi686 — APPROVED** [review]
****

**Comment by pedrobaeza** [comment]
Reverted to previous version.

**Pull request closed without merging**
